name: flutter_calculator
version: 1.0.0+1
publish_to: 'none'
description: A simple calculator app using Flutter.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  math_expressions: ^2.3.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/KALKULATOR.jpg

flutter_native_splash:
  color: "#ffffff"
  image: assets/KALKULATOR.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
